spring.profiles.active=prod

spring.application.name=codesprout
spring.output.ansi.enabled=always
server.port=9093
server.address=0.0.0.0

#SQL
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_HOST:jdbc:mysql://localhost:3306/code_sprout}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#jakson
spring.jackson.mapper.ACCEPT_CASE_INSENSITIVE_ENUMS=true

# === Google OAuth2 Client === [since we are not using server flow except client-id none is required]
spring.security.oauth2.client.registration.google.client-id=758198304615-4re80040l1ksvkoli8n4p3iv4ffeqc3b.apps.googleusercontent.com
