CREATE TABLE otp (
     id VARCHAR(50) PRIMARY KEY,
     otp VARCHAR(10) NOT NULL,
     user_id VARCHAR(50) NOT NULL,
     expire_at TIMESTAMP NOT NULL,
     ip_address VARCHAR(45) NOT NULL,
     user_agent VARCHAR(512) NOT NULL,
     status VARCHAR(20) NOT NULL DEFAULT 'UN_USED',
     reason VARCHAR(50) NOT NULL,
     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
         ON UPDATE CURRENT_TIMESTAMP
);